---
- name: alexandria
  hosts: localhost
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.package:
        name: docker-ce
        state: present
      become: yes
    - name: Run docker-compose up
      community.docker.docker_compose_v2:
        project_src: .
        state: present